# Generated by Django 5.2.5 on 2025-08-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduUsers', '0003_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
    ]
