# Generated by Django 5.2.5 on 2025-08-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduUsers', '0005_profile_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
