# Generated by Django 5.2.5 on 2025-08-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduUsers', '0008_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pic/default.jpg', upload_to='profile_pic/'),
        ),
    ]
