# Generated by Django 5.2.5 on 2025-09-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduUsers', '0009_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='link1',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='link2',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='link3',
            field=models.URLField(blank=True),
        ),
    ]
