# Generated by Django 5.2.5 on 2025-09-04 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduUsers', '0010_profile_link1_profile_link2_profile_link3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='link1',
            new_name='Facebook',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='link2',
            new_name='X',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='link3',
            new_name='instagram',
        ),
    ]
